# Generated by Django 3.2.5 on 2021-08-26 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='city',
            field=models.ForeignKey(default='Бишкек', on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='city',
            field=models.ForeignKey(default='Бишкек', on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='city',
            field=models.ForeignKey(default='Бишкек', on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Город'),
        ),
    ]
